version: "3"
services:
#  parquimetro:
#    image: parquimetro:latest
#    depends_on:
#      - db
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - parquimetro

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parquimetro
    ports:
      - "5432:5432"
    networks:
      - parquimetro


networks:
  parquimetro:
    driver: bridge